import { QuizQuestion } from './types';

export const QUIZ_QUESTIONS: QuizQuestion[] = [
  {
    id: 1,
    number: 1,
    questionSpanish: '¿A quién presenta el señor al invitado?',
    questionArmenian: 'Պարոնը հյուրին ո՞ւմ է ներկայացնում։',
    options: [
      { key: 'A', spanish: 'A su hermana', armenian: 'Իր քրոջը' },
      { key: 'B', spanish: 'A su hija Helena', armenian: 'Իր դստերը՝ Հելենային' },
      { key: 'C', spanish: 'A su esposa', armenian: 'Իր կնոջը' },
      { key: 'D', spanish: 'A su madre', armenian: 'Իր մորը' },
    ],
    correctOptionKey: 'B',
    explanationSpanish: 'Don Rafael presenta formalmente a su hija: «Permítame presentarle a mi hija Helena».',
    explanationArmenian: 'Դոն Ռաֆայելը պաշտոնապես ներկայացնում է իր դստերը՝ «Թույլ տվեք Ձեզ ներկայացնել իմ դստերը՝ Հելենային»։',
    relatedTimestamp: '0:07',
  },
  {
    id: 2,
    number: 2,
    questionSpanish: '¿Qué dice el invitado cuando conoce a Helena?',
    questionArmenian: 'Ի՞նչ է ասում հյուրը, երբ ծանոթանում է Հելենայի հետ։',
    options: [
      { key: 'A', spanish: 'No tengo tiempo.', armenian: 'Ես ժամանակ չունեմ։' },
      { key: 'B', spanish: 'Tengo que marcharme.', armenian: 'Ես պետք է գնամ։' },
      { key: 'C', spanish: 'Es un placer.', armenian: 'Շատ հաճելի է։' },
      { key: 'D', spanish: 'Estoy cansado.', armenian: 'Ես հոգնած եմ։' },
    ],
    correctOptionKey: 'C',
    explanationSpanish: 'Don Alejandro responde con cortesía caballeresca: «Claro, es un placer».',
    explanationArmenian: 'Դոն Ալեխանդրոն ասպետական քաղաքավարությամբ պատասխանում է՝ «Իհարկե, մեծ հաճույք է»։',
    relatedTimestamp: '0:18',
  },
  {
    id: 3,
    number: 3,
    questionSpanish: '¿Qué no ha traído el invitado?',
    questionArmenian: 'Ի՞նչ չի բերել հյուրը։',
    options: [
      { key: 'A', spanish: 'Un obsequio', armenian: 'Նվեր' },
      { key: 'B', spanish: 'Un libro', armenian: 'Գիրք' },
      { key: 'C', spanish: 'Una carta', armenian: 'Նամակ' },
      { key: 'D', spanish: 'Una maleta', armenian: 'Ճամպրուկ' },
    ],
    correctOptionKey: 'A',
    explanationSpanish: 'Don Alejandro se disculpa diciendo: «Temo que no he traído un obsequio para la anfitriona...».',
    explanationArmenian: 'Դոն Ալեխանդրոն ներողամտություն է հայտնում՝ «Վախենամ՝ ես նվեր չեմ բերել տանտիրուհու համար...»։',
    relatedTimestamp: '0:18',
  },
  {
    id: 4,
    number: 4,
    questionSpanish: '¿Qué le pide Helena a don Alejandro?',
    questionArmenian: 'Ի՞նչ է խնդրում Հելենան դոն Ալեխանդրոյից։',
    options: [
      { key: 'A', spanish: 'Que abra la puerta.', armenian: 'Որ բացի դուռը։' },
      { key: 'B', spanish: 'Que busque a su padre.', armenian: 'Որ գտնի իր հորը։' },
      { key: 'C', spanish: 'Que salga de la casa.', armenian: 'Որ դուրս գա տնից։' },
      { key: 'D', spanish: 'Que los acompañe a la mesa.', armenian: 'Որ միանա իրենց սեղանի շուրջ։' },
    ],
    correctOptionKey: 'D',
    explanationSpanish: 'Helena le extiende una invitación formal: «...a mi padre y a mí nos gustaría que nos acompañara a la mesa».',
    explanationArmenian: 'Հելենան հրավիրում է նրան՝ «...իմ հայրն ու ես կցանկանայինք, որ միանայիք մեզ սեղանի շուրջ»։',
    relatedTimestamp: '1:19',
  },
  {
    id: 5,
    number: 5,
    questionSpanish: '¿Cómo responde don Alejandro a la invitación?',
    questionArmenian: 'Ինչպե՞ս է դոն Ալեխանդրոն պատասխանում հրավերին։',
    options: [
      { key: 'A', spanish: 'No puedo quedarme.', armenian: 'Ես չեմ կարող մնալ։' },
      { key: 'B', spanish: 'Eso sería encantador.', armenian: 'Դա հրաշալի կլիներ։' },
      { key: 'C', spanish: 'No tengo hambre.', armenian: 'Ես քաղցած չեմ։' },
      { key: 'D', spanish: 'Quizás mañana.', armenian: 'Գուցե վաղը։' },
    ],
    correctOptionKey: 'B',
    explanationSpanish: 'Don Alejandro acepta encantado con la frase: «Eso sería encantador, señorita».',
    explanationArmenian: 'Դոն Ալեխանդրոն սիրով համաձայնում է՝ «Դա հրաշալի կլիներ, օրիո՛րդ»։',
    relatedTimestamp: '1:37',
  },
  {
    id: 6,
    number: 6,
    questionSpanish: '¿De dónde acaba de llegar don Alejandro?',
    questionArmenian: 'Որտեղի՞ց է նոր ժամանել դոն Ալեխանդրոն։',
    options: [
      { key: 'A', spanish: 'De Francia', armenian: 'Ֆրանսիայից' },
      { key: 'B', spanish: 'De Italia', armenian: 'Իտալիայից' },
      { key: 'C', spanish: 'De España', armenian: 'Իսպանիայից' },
      { key: 'D', spanish: 'De México', armenian: 'Մեքսիկայից' },
    ],
    correctOptionKey: 'C',
    explanationSpanish: 'Se le presenta como: «...don Alejandro del Castillo y García, recién llegado de España».',
    explanationArmenian: 'Նրան ներկայացնում են՝ «...դոն Ալեխանդրո դել Կաստիլյո ի Գարսիային, նոր ժամանած Իսպանիայից»։',
    relatedTimestamp: '1:43',
  },
  {
    id: 7,
    number: 7,
    questionSpanish: '¿A quién presentan como capitán?',
    questionArmenian: 'Ո՞ւմ են ներկայացնում որպես կապիտան։',
    options: [
      { key: 'A', spanish: 'A Harrison Lod', armenian: 'Հարիսոն Լոդին' },
      { key: 'B', spanish: 'A Bernardo', armenian: 'Բեռնարդոյին' },
      { key: 'C', spanish: 'A don Alejandro', armenian: 'Դոն Ալեխանդրոյին' },
      { key: 'D', spanish: 'Al padre de Helena', armenian: 'Հելենայի հորը' },
    ],
    correctOptionKey: 'A',
    explanationSpanish: 'Don Rafael dice: «Él es el capitán Harrison Lod. No es un don, pero es un alma gemela».',
    explanationArmenian: 'Դոն Ռաֆայելն ասում է՝ «Նա կապիտան Հարիսոն Լոդն է: Դոն չէ, բայց հոգու ընկեր է»։',
    relatedTimestamp: '1:47',
  },
  {
    id: 8,
    number: 8,
    questionSpanish: '¿A quién perseguía el capitán?',
    questionArmenian: 'Ո՞ւմ էր հետապնդում կապիտանը։',
    options: [
      { key: 'A', spanish: 'A un comerciante', armenian: 'Մի վաճառականի' },
      { key: 'B', spanish: 'A un viajero', armenian: 'Մի ճանապարհորդի' },
      { key: 'C', spanish: 'A un músico', armenian: 'Մի երաժշտի' },
      { key: 'D', spanish: 'A un bandido legendario', armenian: 'Մի լեգենդար ավազակի' },
    ],
    correctOptionKey: 'D',
    explanationSpanish: 'Alejandro indaga: «¿No es la persona que perseguía a un legendario bandido el otro día?».',
    explanationArmenian: 'Ալեխանդրոն հարցնում է՝ «Մի՞թե սա այն անձնավորությունը չէ, որ հետապնդում էր լեգենդար ավազակին օրերս»։',
    relatedTimestamp: '1:57',
  },
  {
    id: 9,
    number: 9,
    questionSpanish: '¿Qué pregunta alguien sobre el bandido?',
    questionArmenian: 'Ի՞նչ է հարցնում ինչ-որ մեկը ավազակի մասին։',
    options: [
      { key: 'A', spanish: '¿Dónde vive?', armenian: 'Որտե՞ղ է նա ապրում։' },
      { key: 'B', spanish: '¿Y lo capturó?', armenian: 'Իսկ բռնեցի՞ք նրան։' },
      { key: 'C', spanish: '¿Cómo se llama?', armenian: 'Ի՞նչ է նրա անունը։' },
      { key: 'D', spanish: '¿Cuántos años tiene?', armenian: 'Քանի՞ տարեկան է նա։' },
    ],
    correctOptionKey: 'B',
    explanationSpanish: 'Se pregunta con suspicacia: «¿Y lo capturó?», buscando confirmar el fracaso del capitán.',
    explanationArmenian: 'Հետաքրքրվում են՝ «¿Y lo capturó?» (Իսկ բռնեցի՞ք նրան), ինչին նա պատասխանում է՝ «Դա կլինի շուտով»։',
    relatedTimestamp: '2:03',
  },
  {
    id: 10,
    number: 10,
    questionSpanish: '¿Qué se dice sobre el bandido?',
    questionArmenian: 'Ի՞նչ են ասում ավազակի մասին։',
    options: [
      { key: 'A', spanish: 'Que está en la cárcel.', armenian: 'Որ նա բանտում է։' },
      { key: 'B', spanish: 'Que ha regresado a España.', armenian: 'Որ նա վերադարձել է Իսպանիա։' },
      { key: 'C', spanish: 'Que tal vez escapó.', armenian: 'Որ հնարավոր է՝ նա փախել է։' },
      { key: 'D', spanish: 'Que está en la mesa.', armenian: 'Որ նա սեղանի մոտ է։' },
    ],
    correctOptionKey: 'C',
    explanationSpanish: 'Don Alejandro comenta con sutileza: «Bueno, el bandido tal vez escapó, pero nosotros lo pensaremos dos veces antes de ir a confesarnos».',
    explanationArmenian: 'Դոն Ալեխանդրոն նրբորեն ասում է՝ «Դե, ավազակը հնարավոր է փախավ, բայց մենք երկու անգամ կմտածենք նախքան խոստովանության գնալը»։',
    relatedTimestamp: '2:10',
  },
];
